export const PHASE14_WORKFLOW_ROUTES = [
  { area: 'Laboratory Queue', method: 'GET', path: '/api/lab/queue' },
  { area: 'Laboratory Queue Summary', method: 'GET', path: '/api/lab/queue/summary' },
  { area: 'Laboratory Queue Search', method: 'GET', path: '/api/lab/queue/search' },
  { area: 'Laboratory Accept Selected Tests', method: 'POST', path: '/api/lab/queue/:orderId/accept-tests' },
  { area: 'Accepted Samples', method: 'GET', path: '/api/lab/accepted-samples' },
  { area: 'Accepted Sample Detail', method: 'GET', path: '/api/lab/accepted-samples/:sampleId' },
  { area: 'Save Per-Test Lab Result', method: 'POST', path: '/api/lab/accepted-samples/:sampleId/tests/:testId/result' },
  { area: 'Complete Per-Test Lab Result', method: 'PATCH', path: '/api/lab/accepted-samples/:sampleId/tests/:testId/complete' },
  { area: 'Upload Per-Test Lab Document', method: 'POST', path: '/api/lab/accepted-samples/:sampleId/tests/:testId/documents' },
  { area: 'Push Lab Result To Clinician', method: 'POST', path: '/api/lab/accepted-samples/:sampleId/push-to-clinician' },
  { area: 'Lab Results Archive', method: 'GET', path: '/api/lab/results' },
  { area: 'Scan Queue', method: 'GET', path: '/api/scan/queue' },
  { area: 'Scan Queue Summary', method: 'GET', path: '/api/scan/queue/summary' },
  { area: 'Accept Scan Request', method: 'POST', path: '/api/scan/queue/:orderId/accept' },
  { area: 'Accepted Scans', method: 'GET', path: '/api/scan/accepted' },
  { area: 'Save Scan Result', method: 'POST', path: '/api/scan/accepted/:scanId/result' },
  { area: 'Complete Scan Result', method: 'PATCH', path: '/api/scan/accepted/:scanId/complete' },
  { area: 'Upload Scan Document', method: 'POST', path: '/api/scan/accepted/:scanId/documents' },
  { area: 'Push Scan Result To Clinician', method: 'POST', path: '/api/scan/accepted/:scanId/push-to-clinician' },
  { area: 'Reception Walk-ins', method: 'GET', path: '/api/reception/walk-ins' },
  { area: 'Create Walk-in', method: 'POST', path: '/api/reception/walk-ins' },
  { area: 'Reception Request Labs', method: 'POST', path: '/api/reception/walk-ins/:patientId/request-labs' },
  { area: 'Reception Request Scans', method: 'POST', path: '/api/reception/walk-ins/:patientId/request-scans' },
  { area: 'Reception Reference Copies', method: 'GET', path: '/api/reception/results/reference-copies' },
  { area: 'Clinician Results Inbox', method: 'GET', path: '/api/clinician/results' },
  { area: 'Clinician Result Detail', method: 'GET', path: '/api/clinician/results/:inboxId' },
  { area: 'Clinician Result Documents', method: 'GET', path: '/api/clinician/results/:inboxId/documents' },
  { area: 'Mark Result Read', method: 'PATCH', path: '/api/clinician/results/:inboxId/read' },
  { area: 'Archive Result', method: 'PATCH', path: '/api/clinician/results/:inboxId/archive' },
  { area: 'Admin Facilities', method: 'GET', path: '/api/admin/facilities' },
  { area: 'Create Facility', method: 'POST', path: '/api/admin/facilities' },
  { area: 'Update Facility Features', method: 'PATCH', path: '/api/admin/facilities/:facilityId/features' },
  { area: 'Update Facility Departments', method: 'PATCH', path: '/api/admin/facilities/:facilityId/departments' },
  { area: 'Update Facility Catalog', method: 'PATCH', path: '/api/admin/facilities/:facilityId/catalog' },
  { area: 'Admin Workflow Events', method: 'GET', path: '/api/admin/workflow-events' },
] as const;

export const PHASE14_REQUIRED_DATABASE_TABLES = [
  'DiagnosticFacility',
  'FacilityFeature',
  'FacilityDepartment',
  'FacilityServiceCatalog',
  'FacilityRoutingRule',
  'FacilityLimit',
  'FacilityUserAssignment',
  'LabAcceptedSample',
  'LabAcceptedSampleTest',
  'LabTestResultDocument',
  'ScanAcceptedRequest',
  'ScanResultDocument',
  'ResultDeliveryInbox',
  'facility_workflow_events',
  'workflow_notification_delivery_logs',
] as const;

export const PHASE14_WORKFLOW_CHECKLIST = [
  'Facility scoping is enabled for lab, scan, reception, clinician, and admin facility routes.',
  'Lab queue accepts only selected requested tests.',
  'Accepted samples show only accepted tests.',
  'Each accepted lab test can be completed independently.',
  'Result documents are linked to the exact test result.',
  'Results cannot be pushed until accepted tests are complete.',
  'Lab and scan results are delivered directly to clinician inbox.',
  'Reception routes requests directly to diagnostic queues.',
  'Sent results stay in lab/scan results archive.',
  'Workflow events and audit logs are created for critical actions.',
] as const;
