export const WORKFLOW_EVENT_GROUPS = {
  FACILITY: 'FACILITY',
  RECEPTION: 'RECEPTION',
  LABORATORY: 'LABORATORY',
  SCAN: 'SCAN',
  RESULTS: 'RESULTS',
  DOCUMENTS: 'DOCUMENTS',
  BILLING: 'BILLING',
  USERS: 'USERS',
} as const;

export const WORKFLOW_ENTITY_TYPES = {
  FACILITY: 'FACILITY',
  USER: 'USER',
  PATIENT: 'PATIENT',
  ORDER: 'ORDER',
  LAB_ACCEPTED_SAMPLE: 'LAB_ACCEPTED_SAMPLE',
  LAB_TEST_RESULT: 'LAB_TEST_RESULT',
  SCAN_ACCEPTED_REQUEST: 'SCAN_ACCEPTED_REQUEST',
  RESULT_DELIVERY: 'RESULT_DELIVERY',
  DOCUMENT: 'DOCUMENT',
  INVOICE: 'INVOICE',
  PAYMENT: 'PAYMENT',
} as const;

export const WORKFLOW_EVENT_TYPES = {
  FACILITY_CREATED: 'FACILITY_CREATED',
  FACILITY_UPDATED: 'FACILITY_UPDATED',
  FACILITY_STATUS_CHANGED: 'FACILITY_STATUS_CHANGED',
  FACILITY_FEATURES_UPDATED: 'FACILITY_FEATURES_UPDATED',
  FACILITY_DEPARTMENTS_UPDATED: 'FACILITY_DEPARTMENTS_UPDATED',
  FACILITY_CATALOG_UPDATED: 'FACILITY_CATALOG_UPDATED',
  FACILITY_ROUTING_UPDATED: 'FACILITY_ROUTING_UPDATED',
  FACILITY_BRANDING_UPDATED: 'FACILITY_BRANDING_UPDATED',
  FACILITY_LIMITS_UPDATED: 'FACILITY_LIMITS_UPDATED',

  FACILITY_USER_ASSIGNED: 'FACILITY_USER_ASSIGNED',
  FACILITY_USER_REMOVED: 'FACILITY_USER_REMOVED',

  RECEPTION_WALKIN_CREATED: 'RECEPTION_WALKIN_CREATED',
  RECEPTION_LAB_REQUEST_CREATED: 'RECEPTION_LAB_REQUEST_CREATED',
  RECEPTION_SCAN_REQUEST_CREATED: 'RECEPTION_SCAN_REQUEST_CREATED',

  LAB_REQUEST_RECEIVED: 'LAB_REQUEST_RECEIVED',
  LAB_TESTS_ACCEPTED: 'LAB_TESTS_ACCEPTED',
  LAB_RESULT_SAVED: 'LAB_RESULT_SAVED',
  LAB_TEST_COMPLETED: 'LAB_TEST_COMPLETED',
  LAB_SAMPLE_COMPLETED: 'LAB_SAMPLE_COMPLETED',
  LAB_DOCUMENT_UPLOADED: 'LAB_DOCUMENT_UPLOADED',
  LAB_DOCUMENT_REMOVED: 'LAB_DOCUMENT_REMOVED',
  LAB_RESULT_SENT_TO_CLINICIAN: 'LAB_RESULT_SENT_TO_CLINICIAN',

  SCAN_REQUEST_RECEIVED: 'SCAN_REQUEST_RECEIVED',
  SCAN_REQUEST_ACCEPTED: 'SCAN_REQUEST_ACCEPTED',
  SCAN_RESULT_SAVED: 'SCAN_RESULT_SAVED',
  SCAN_RESULT_COMPLETED: 'SCAN_RESULT_COMPLETED',
  SCAN_DOCUMENT_UPLOADED: 'SCAN_DOCUMENT_UPLOADED',
  SCAN_DOCUMENT_REMOVED: 'SCAN_DOCUMENT_REMOVED',
  SCAN_RESULT_SENT_TO_CLINICIAN: 'SCAN_RESULT_SENT_TO_CLINICIAN',

  CLINICIAN_RESULT_DELIVERED: 'CLINICIAN_RESULT_DELIVERED',
  CLINICIAN_RESULT_READ: 'CLINICIAN_RESULT_READ',
  CLINICIAN_RESULT_ARCHIVED: 'CLINICIAN_RESULT_ARCHIVED',

  INVOICE_CREATED: 'INVOICE_CREATED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
} as const;

export const WORKFLOW_NOTIFICATION_AUDIENCE = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  FACILITY_ADMIN: 'FACILITY_ADMIN',
  CLINICIAN: 'CLINICIAN',
  LAB_STAFF: 'LAB_STAFF',
  SCAN_STAFF: 'SCAN_STAFF',
  RECEPTIONIST: 'RECEPTIONIST',
  CASHIER: 'CASHIER',
} as const;

export const WORKFLOW_SEVERITY = {
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
  CRITICAL: 'CRITICAL',
} as const;

export const WORKFLOW_NOTIFICATION_CHANNELS = {
  IN_APP: 'IN_APP',
  EMAIL: 'EMAIL',
  SMS: 'SMS',
} as const;

export const DEFAULT_WORKFLOW_PAGE_SIZE = 25;
export const MAX_WORKFLOW_PAGE_SIZE = 100;
