export const phase13DemoFacilities = [
  {
    id: 'fac_sunkwa_main',
    name: 'Sunkwa Diagnostic Centre',
    code: 'SUNKWA-MAIN',
    type: 'DIAGNOSTIC_CENTER',
    status: 'ACTIVE',
    phone: '+233 30 000 1000',
    email: 'info@sunkwadiagnostics.local',
    address: 'Main diagnostic facility',
    city: 'Accra',
    region: 'Greater Accra',
    country: 'Ghana',
    logoName: 'SUNKWA',
    primaryColor: '#2f2925',
    secondaryColor: '#efe5d5',
    notes: 'Default facility for full platform workflow testing.',
  },
  {
    id: 'fac_eastern_lab',
    name: 'Eastern Partner Laboratory',
    code: 'EASTERN-LAB',
    type: 'PARTNER_LAB',
    status: 'ACTIVE',
    phone: '+233 30 000 2000',
    email: 'lab@easternpartner.local',
    address: 'Partner laboratory branch',
    city: 'Koforidua',
    region: 'Eastern Region',
    country: 'Ghana',
    logoName: 'EASTERN LAB',
    primaryColor: '#3b302a',
    secondaryColor: '#f3eadc',
    notes: 'Lab-only facility used to verify feature customization.',
  },
  {
    id: 'fac_imaging_partner',
    name: 'Community Imaging Partner',
    code: 'IMG-PARTNER',
    type: 'IMAGING_CENTER',
    status: 'ACTIVE',
    phone: '+233 30 000 3000',
    email: 'imaging@partner.local',
    address: 'Partner imaging facility',
    city: 'Kumasi',
    region: 'Ashanti Region',
    country: 'Ghana',
    logoName: 'IMAGING PARTNER',
    primaryColor: '#292929',
    secondaryColor: '#eee2d0',
    notes: 'Scan-only facility used to verify module restrictions.',
  },
];

export const phase13FacilityFeatures = [
  'clinician_portal',
  'reception',
  'walk_in_requests',
  'laboratory',
  'scan_imaging',
  'billing',
  'payments',
  'file_uploads',
  'result_delivery',
  'reports',
  'notifications',
  'audit_logs',
];

export const phase13FacilityDepartments = [
  { key: 'reception', name: 'Reception' },
  { key: 'laboratory', name: 'Laboratory' },
  { key: 'radiology', name: 'Radiology / Scan Unit' },
  { key: 'billing', name: 'Billing / Finance' },
  { key: 'admin', name: 'Administration' },
];

export const phase13LabCatalog = [
  { code: 'FBC', name: 'Full Blood Count', department: 'laboratory', price: 80, turnaroundHours: 4, referenceRange: 'See differential report' },
  { code: 'MALARIA-RDT', name: 'Malaria Rapid Diagnostic Test', department: 'laboratory', price: 35, turnaroundHours: 1, referenceRange: 'Negative' },
  { code: 'HB', name: 'Hemoglobin', department: 'laboratory', price: 30, turnaroundHours: 2, referenceRange: 'Male 13.5-17.5 g/dL; Female 12.0-15.5 g/dL' },
  { code: 'LFT', name: 'Liver Function Test', department: 'laboratory', price: 140, turnaroundHours: 6, referenceRange: 'Panel dependent' },
  { code: 'RFT', name: 'Renal Function Test', department: 'laboratory', price: 130, turnaroundHours: 6, referenceRange: 'Panel dependent' },
  { code: 'LIPID', name: 'Lipid Profile', department: 'laboratory', price: 120, turnaroundHours: 8, referenceRange: 'Panel dependent' },
  { code: 'HBA1C', name: 'HbA1c', department: 'laboratory', price: 150, turnaroundHours: 8, referenceRange: '< 5.7%' },
  { code: 'URINALYSIS', name: 'Urinalysis', department: 'laboratory', price: 45, turnaroundHours: 2, referenceRange: 'Normal microscopy/chemistry' },
];

export const phase13ScanCatalog = [
  { code: 'XR-CHEST', name: 'Chest X-ray', department: 'radiology', price: 180, turnaroundHours: 3 },
  { code: 'US-ABD', name: 'Abdominal Ultrasound', department: 'radiology', price: 260, turnaroundHours: 4 },
  { code: 'US-PEL', name: 'Pelvic Ultrasound', department: 'radiology', price: 260, turnaroundHours: 4 },
  { code: 'CT-HEAD', name: 'CT Head', department: 'radiology', price: 750, turnaroundHours: 8 },
  { code: 'MRI-LUMBAR', name: 'MRI Lumbar Spine', department: 'radiology', price: 1500, turnaroundHours: 24 },
];
