export const CLINICIAN_RESULT_DELIVERY_STATUS = {
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  READ: 'READ',
  ARCHIVED: 'ARCHIVED',
} as const;

export const CLINICIAN_RESULT_SOURCE = {
  LAB: 'LAB',
  SCAN: 'SCAN',
  MANUAL: 'MANUAL',
} as const;

export const CLINICIAN_RESULT_PRIORITY = {
  ROUTINE: 'ROUTINE',
  URGENT: 'URGENT',
  STAT: 'STAT',
} as const;

export const CLINICIAN_RESULT_NOTIFICATION_TYPES = {
  RESULT_SENT_TO_CLINICIAN: 'RESULT_SENT_TO_CLINICIAN',
  RESULT_READ_BY_CLINICIAN: 'RESULT_READ_BY_CLINICIAN',
  RESULT_ARCHIVED_BY_CLINICIAN: 'RESULT_ARCHIVED_BY_CLINICIAN',
} as const;

export const CLINICIAN_RESULT_PAGE_LIMITS = {
  DEFAULT_TAKE: 50,
  MAX_TAKE: 100,
} as const;
