export const FACILITY_STATUS = {
  ACTIVE: 'ACTIVE',
  SETUP: 'SETUP',
  SUSPENDED: 'SUSPENDED',
  DISABLED: 'DISABLED',
} as const;

export const FACILITY_TYPES = {
  DIAGNOSTIC_CENTER: 'DIAGNOSTIC_CENTER',
  HOSPITAL_LAB: 'HOSPITAL_LAB',
  IMAGING_CENTER: 'IMAGING_CENTER',
  POLYCLINIC: 'POLYCLINIC',
  PARTNER: 'PARTNER',
} as const;

export const FACILITY_FEATURE_KEYS = {
  LABORATORY: 'laboratory',
  SCAN_IMAGING: 'scan_imaging',
  BILLING: 'billing',
  RECEPTION: 'reception',
  CLINICIAN_PORTAL: 'clinician_portal',
  WALK_IN_REQUESTS: 'walk_in_requests',
  RESULT_DOCUMENT_UPLOADS: 'result_document_uploads',
  DIRECT_CLINICIAN_DELIVERY: 'direct_clinician_delivery',
  REPORTS: 'reports',
  NOTIFICATIONS: 'notifications',
  FINANCE: 'finance',
} as const;

export const FACILITY_DEPARTMENT_KEYS = {
  LABORATORY: 'laboratory',
  RADIOLOGY: 'radiology',
  ULTRASOUND: 'ultrasound',
  CT_SCAN: 'ct_scan',
  MRI: 'mri',
  RECEPTION: 'reception',
  FINANCE: 'finance',
  ADMINISTRATION: 'administration',
} as const;

export const FACILITY_SERVICE_TYPES = {
  LAB: 'LAB',
  SCAN: 'SCAN',
  OTHER: 'OTHER',
} as const;

export const FACILITY_LIMIT_KEYS = {
  USERS: 'users',
  CLINICIANS: 'clinicians',
  DAILY_ORDERS: 'daily_orders',
  MONTHLY_ORDERS: 'monthly_orders',
  STORAGE_GB: 'storage_gb',
} as const;

export const FACILITY_ROUTING_RECIPIENTS = {
  CLINICIAN: 'CLINICIAN',
  FACILITY_ADMIN: 'FACILITY_ADMIN',
  RECEPTION_REFERENCE_ONLY: 'RECEPTION_REFERENCE_ONLY',
} as const;

export const FACILITY_AUDIT_EVENTS = {
  CREATED: 'FACILITY_CREATED',
  UPDATED: 'FACILITY_UPDATED',
  STATUS_CHANGED: 'FACILITY_STATUS_CHANGED',
  FEATURES_UPDATED: 'FACILITY_FEATURES_UPDATED',
  DEPARTMENTS_UPDATED: 'FACILITY_DEPARTMENTS_UPDATED',
  CATALOG_UPDATED: 'FACILITY_CATALOG_UPDATED',
  ROUTING_UPDATED: 'FACILITY_ROUTING_UPDATED',
  BRANDING_UPDATED: 'FACILITY_BRANDING_UPDATED',
  LIMITS_UPDATED: 'FACILITY_LIMITS_UPDATED',
  USER_ASSIGNED: 'FACILITY_USER_ASSIGNED',
  USER_REMOVED: 'FACILITY_USER_REMOVED',
} as const;

export const DEFAULT_FACILITY_FEATURES = [
  FACILITY_FEATURE_KEYS.LABORATORY,
  FACILITY_FEATURE_KEYS.SCAN_IMAGING,
  FACILITY_FEATURE_KEYS.RECEPTION,
  FACILITY_FEATURE_KEYS.CLINICIAN_PORTAL,
  FACILITY_FEATURE_KEYS.WALK_IN_REQUESTS,
  FACILITY_FEATURE_KEYS.RESULT_DOCUMENT_UPLOADS,
  FACILITY_FEATURE_KEYS.DIRECT_CLINICIAN_DELIVERY,
  FACILITY_FEATURE_KEYS.NOTIFICATIONS,
];

export const DEFAULT_FACILITY_DEPARTMENTS = [
  { departmentKey: FACILITY_DEPARTMENT_KEYS.LABORATORY, departmentName: 'Laboratory' },
  { departmentKey: FACILITY_DEPARTMENT_KEYS.RADIOLOGY, departmentName: 'Radiology / Imaging' },
  { departmentKey: FACILITY_DEPARTMENT_KEYS.RECEPTION, departmentName: 'Reception' },
  { departmentKey: FACILITY_DEPARTMENT_KEYS.ADMINISTRATION, departmentName: 'Administration' },
];
