export const RECEPTION_SOURCE = {
  WALK_IN: 'RECEPTION_WALK_IN',
  EXISTING_PATIENT: 'RECEPTION_EXISTING_PATIENT',
} as const;

export const RECEPTION_REQUEST_TYPE = {
  LAB: 'LAB',
  SCAN: 'SCAN',
} as const;

export const RECEPTION_ORDER_STATUS = {
  QUEUED: 'QUEUED',
  CANCELLED: 'CANCELLED',
} as const;

export const RECEPTION_PRIORITY = {
  ROUTINE: 'ROUTINE',
  URGENT: 'URGENT',
  STAT: 'STAT',
} as const;

export const RECEPTION_NOTIFICATION_TYPES = {
  WALK_IN_REGISTERED: 'WALK_IN_REGISTERED',
  WALK_IN_LAB_REQUEST_CREATED: 'WALK_IN_LAB_REQUEST_CREATED',
  WALK_IN_SCAN_REQUEST_CREATED: 'WALK_IN_SCAN_REQUEST_CREATED',
} as const;

export const RECEPTION_PAGE_LIMITS = {
  DEFAULT_TAKE: 50,
  MAX_TAKE: 100,
} as const;
